Repository 9atrotte/13IA, pull requests merged in 2023-08, with the labels that each got.

#76 Pool points table
  Assets/SponsorsLogos/uni.png
  Release/Images/icon.png
  Release/Images/uni.png
  Release/index.html
  Release/results.html
  Release/rules.html
  Release/scripts/index.js
  Release/styles/homePage.css
  Release/styles/index.css
  Release/styles/results.css
Labels: enhancement

#77 Maps page
  Assets/hbhswebsite/Thumbs.db
  MockUp/Maps.html
  MockUp/Results.html
  MockUp/index.css
  MockUp/maps.css
  MockUp/maps.js
Labels: enhancement

#78 Teams page
  MockUp/Teams.html
  MockUp/index.js
  MockUp/teams.css
  MockUp/teams.js
Labels: enhancement

#83 Hotfix 1.3
  Release/index.html
  Release/results.html
  Release/rules.html
  Release/styles/homePage.css
Labels: enhancement

#84 Hotfix 1.3
  Release/index.html
  Release/results.html
  Release/rules.html
  Release/scripts/index.js
  Release/styles/homePage.css
  Release/styles/index.css
Labels: enhancement

#90 Pearents page
  Assets/u15tournamentwebsitestuff/U15TournamentParentsEveningRegistration.png
  Release/Images/U15TournamentParentsEveningRegistration.png
  Release/index.html
  Release/results.html
  Release/styles/index.css
  Release/styles/supporters.css
  Release/supporters.html
  Scripts/TeamsCard/obj/Debug/net7.0/TeamsCard.assets.cache
  Scripts/TeamsCard/obj/project.nuget.cache
  Scripts/TeamsCardMaker/.vscode/settings.json
  Scripts/TeamsCardMaker/TeamsCard/Program.cs
  Scripts/TeamsCardMaker/TeamsCard/TeamsCard.csproj
  Scripts/TeamsCardMaker/TeamsCard/TeamsCard.sln
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.AssemblyInfo.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.AssemblyInfoInputs.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.GeneratedMSBuildEditorConfig.editorconfig
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.GlobalUsings.g.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.assets.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.AssemblyReference.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.CoreCompileInputs.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.FileListAbsolute.txt
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.dgspec.json
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.g.props
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.g.targets
  Scripts/TeamsCardMaker/TeamsCard/obj/project.assets.json
  Scripts/TeamsCardMaker/TeamsCard/obj/project.nuget.cache
  Scripts/tableMaker/tableMaker/Program.cs
Labels: enhancement, INPORTANT

#91 Release 2.0
  Assets/u15tournamentwebsitestuff/U15TournamentParentsEveningRegistration.png
  Release/Images/U15TournamentParentsEveningRegistration.png
  Release/index.html
  Release/results.html
  Release/styles/homePage.css
  Release/styles/index.css
  Release/styles/supporters.css
  Release/supporters.html
  Scripts/TeamsCard/obj/Debug/net7.0/TeamsCard.assets.cache
  Scripts/TeamsCard/obj/project.nuget.cache
  Scripts/TeamsCardMaker/.vscode/settings.json
  Scripts/TeamsCardMaker/TeamsCard/Program.cs
  Scripts/TeamsCardMaker/TeamsCard/TeamsCard.csproj
  Scripts/TeamsCardMaker/TeamsCard/TeamsCard.sln
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.AssemblyInfo.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.AssemblyInfoInputs.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.GeneratedMSBuildEditorConfig.editorconfig
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.GlobalUsings.g.cs
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.assets.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.AssemblyReference.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.CoreCompileInputs.cache
  Scripts/TeamsCardMaker/TeamsCard/obj/Debug/net7.0/TeamsCard.csproj.FileListAbsolute.txt
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.dgspec.json
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.g.props
  Scripts/TeamsCardMaker/TeamsCard/obj/TeamsCard.csproj.nuget.g.targets
  Scripts/TeamsCardMaker/TeamsCard/obj/project.assets.json
  Scripts/TeamsCardMaker/TeamsCard/obj/project.nuget.cache
  Scripts/tableMaker/tableMaker/Program.cs
Labels: enhancement, INPORTANT

#96 Release 3.0
  Release/maps.html
  Release/scripts/maps.js
Labels: enhancement

#100 fixing header
  Release/index.html
  Release/maps.html
  Release/results.html
  Release/rules.html
  Release/supporters.html
Labels: bug, enhancement

#103 fixed grammer #102
  Release/index.html
  Scripts/tableMaker/input.csv
Labels: bug

#119 Hot fix 4.0.5
  Release/Images/TeamSponsors/4slogo.jpg
  Release/Images/TeamSponsors/cmg.png
  Release/Images/TeamSponsors/hunterCivil.jpg
  Release/Images/TeamSponsors/hydrilllogo.jpg
  Release/index.html
  Release/teams.html
Labels: bug

#122 rbhs sposnor and name changes
  Release/Images/TeamSponsors/expandasign.png
  Release/Images/TeamSponsors/grb.png
  Release/Images/TeamSponsors/profilesGym.png
  Release/Images/TeamSponsors/timberLands.png
  Release/teams.html
Labels: bug

#124 99 responsive design
  Release/maps.html
  Release/scripts/index.js
  Release/scripts/maps.js
  Release/scripts/teams.js
  Release/styles/homePage.css
  Release/styles/index.css
  Release/styles/maps.css
  Release/styles/results.css
  Release/styles/teams.css
  Scripts/TeamsCardMaker/text.txt
Labels: enhancement

#125 Release 5.0.0
  Release/maps.html
  Release/scripts/index.js
  Release/scripts/maps.js
  Release/scripts/teams.js
  Release/styles/homePage.css
  Release/styles/index.css
  Release/styles/maps.css
  Release/styles/results.css
  Release/styles/teams.css
  Scripts/TeamsCardMaker/text.txt
Labels: enhancement

#129 testing headmaster show more
  Release/index.html
  Release/scripts/homePage.js
  Release/scripts/index.js
  Release/styles/homePage.css
  Scripts/tableMaker/tableMaker/obj/Debug/net6.0/tableMaker.GeneratedMSBuildEditorConfig.editorconfig
  Scripts/tableMaker/tableMaker/obj/Debug/net6.0/tableMaker.assets.cache
Labels: enhancement
